sudo: required
services:
  - docker

before_install:
  - docker build -t wesyoung1/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run wesyoung1/react-test npm test -- --coverage
  # could add additional scripts here and builds above to test the other projects, 
  # instead of just testing the client project

after_success:
  - docker build -t wesyoung1/multi-client ./client
  - docker build -t wesyoung1/multi-nginx ./nginx
  - docker build -t wesyoung1/multi-server ./server
  - docker build -t wesyoung1/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to docker hub
  - docker push wesyoung1/multi-client
  - docker push wesyoung1/multi-nginx
  - docker push wesyoung1/multi-server
  - docker push wesyoung1/multi-worker
